urls.py
from django.urls import path

from . import views

app_name = 'snekboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('<b>/', views.postsPage, name='postsPage'),
    path('<b>/<int:p>/', views.postsPage, name='postsPage'),
    path('<b>/catalog/', views.catalog, name='catalog'),
    path('<b>/res/<int:p>', views.post, name='post'),
    path('<b>/post', views.postapi, name='postapi'),
    path('<b>/delete', views.postdelete, name='postdelete'),
]

models.py
from django.db import models
import re

# Create your models here.
class Board(models.Model):
    boardUrl = models.CharField(max_length=5)
    boardTitle = models.CharField(max_length=100)
    hidden = models.BooleanField()
    lastPost = models.IntegerField(default=0)
    def __str__(self):
        return self.boardUrl

class Post(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    postContent = models.TextField(max_length=1000)
    mail = models.CharField(blank=True, max_length=20)
    password = models.CharField(max_length=64) #sha256 digest in hex
    ip = models.GenericIPAddressField(protocol='both')
    postDate = models.DateTimeField()
    postId = models.IntegerField()
    parentId = models.IntegerField(default=0)
    def __str__(self):
        return "{}/{}".format(self.board.boardUrl, self.postId)

class Wordfilter(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    pattern = models.CharField(max_length=255)
    repl = models.CharField(max_length=255)
    def apply(self, input_):
        return re.sub(self.pattern, self.repl, input_)

'''class Attachment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    fname = models.TextField(max_length=100)
    upload = models.FileField(upload_to=\
            '/'+self.post.board.boardUrl+'/res/%s')'''

views.py
from django.shortcuts import get_object_or_404 as get404, render
from django.http import *
from django.urls import reverse

from .models import Board, Post, Wordfilter

from hashlib import sha256
import datetime
from math import ceil
from django.contrib.auth.hashers import make_password, check_password

# Create your views here.

### HELPERS ###
def preprocess(text):
    text = text.replace('&', '&amp;')\
               .replace('<', '&lt;')\
               .replace('>', '&gt;')\
               .replace('\n', '<br>') #html escape

    text = text.replace('[b]', '<b>')\
               .replace('[/b]', '</b>')\
               .replace('[i]', '<i>')\
               .replace('[/i]', '</i>')\
               .replace('[u]', '<u>')\
               .replace('[/u]', '</u>')\
               .replace('[s]', '<s>')\
               .replace('[/s]', '</s>')\
               .replace('[code]', '<pre>')\
               .replace('[/code]', '</pre>') #bbcode

    return text

### VIEWS ###
def index(request):
    return render(request, 'snekboard/index.html')

POSTS_PER_PAGE = 5
def postsPage(request, b, p=1):
    board = get404(Board, boardUrl=b)
    posts = Post.objects.order_by('-postDate')
    parents = []
    for i in posts: # get threads sorted by last bump
        if i.parentId != 0:
            if i.mail != 'sage':
                parent = Post.objects.get(pk=i.parentId)
                if parent not in parents:
                    parents.append(parent)
        else:
            if i not in parents:
                parents.append(i)
    pages = ceil(len(parents) / POSTS_PER_PAGE)
    if pages < p: #there isn't a page 11 if there are 10 pages
        raise Http404
    last = []
    parents = parents[::-1] # reverse because paginator reverses
    for i in range( ((p-1)*POSTS_PER_PAGE)+1, p*POSTS_PER_PAGE+1):
        #paginate
        try:
            last.append(parents[0-i])
        except IndexError: #if not full page
            pass
    threads = []
    for i in last:
        ans = Post.objects.filter(parentId=i.postId).order_by('-postId')
        show = ans[:3][::-1]
        skipped = len(ans)-3 if len(ans) > 3 else 0
        threads.append([i, skipped, show])
    return render(request, 'snekboard/postsPage.html',
            {'t': threads, 'b': board, 'p': range(1, pages+1)})

def catalog(request, b):
    board = get404(Board, boardUrl=b)
    posts = Post.objects.order_by('-postDate')
    parents = []
    for i in posts: # get threads sorted by last bump
        if i.parentId != 0:
            if i.mail != 'sage':
                parent = Post.objects.get(pk=i.parentId)
                if parent not in parents:
                    parents.append(parent)
        else:
            if i not in parents:
                parents.append(i)
    posts = []
    for i in parents:
        posts.append({'mail': i.mail, 'postDate': i.postDate,
            'answ': Post.objects.filter(parentId=i.postId).count(),
            'postContent': i.postContent})
    return render(request, 'snekboard/catalog.html',
            {'b': board, 'posts': posts})

def post(request, b, p):
    post = get404(Post, board__boardUrl=b, postId=p)
    board = get404(Board, boardUrl=b)
    if post.parentId == 0:
        try:
            pid = post.postId
            ans = Post.objects.filter(parentId=pid)
        except DoesNotExist:
            ans = []
        return render(request, 'snekboard/post.html',
                {'b': board, 'post': post, 'ans': ans })
    else:
        return HttpResponseRedirect(reverse('snekboard:post', args=(b, post.parentId)))

def postapi(request, b):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])
    board = get404(Board, boardUrl=b)
    pid = board.lastPost + 1
    P = request.POST
    if None in [P['msg'], P['mail'], P['parent'], P['pass']]:
        return HttpResponseBadRequest()
    if len(P['msg']) > 1000 or len(P['mail']) > 20:
        return HttpResponseBadRequest()
    msg = preprocess(P['msg'])
    for i in Wordfilter.objects.filter(board=board):
        msg = i.apply(msg)
    if int(P['parent']) != 0:
        if Post.objects.get(pk=P['parent']).parentId != 0:
            return HttpResponseBadRequest()
    p = Post(board=board, postContent=msg, mail=P['mail'],
             password = make_password(P['pass']),
             ip = request.META.get('X_FORWARDED_FOR') or \
                     request.META['REMOTE_ADDR'],
             postDate = datetime.datetime.now(), postId=pid,
             parentId = P['parent'])
    p.save()
    board.lastPost = pid
    board.save()
    return HttpResponseRedirect(reverse('snekboard:post', args=(b, p.postId)))

def postdelete(request, b):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])
    board = get404(Board, boardUrl=b)
    P = request.POST
    if None in [P['post'], P['pass']]:
        return HttpResponseBadRequest()
    post = get404(Post, postId=P['post'], board=board)
    if check_password(P['pass'], post.password):
        parent = post.parentId
        if parent != 0:
            post.delete()
            return HttpResponseRedirect(reverse('snekboard:post', args=(b, parent)))
        else:
            for i in Post.objects.filter(parentId=post.postId):
                i.delete()
            post.delete()
            return HttpResponseRedirect(reverse('snekboard:postsPage', args=(b, 1)))
    else:
        return HttpResponseForbidden('Wrong password')

templates/snekboard/catalog.html
{% load snekboard_postprocess %}
<center>
  <h1>/{{ b.boardUrl }}/</h1>
  <h2>{{ b.boardTitle }}</h2>
</center>
<hr>
<style>
.tile {
        display: inline-block;
        width: 10em;
        border: 1px solid black;
        margin: 0.5em;
}
.tile-container {
        width: 100%;
}
</style>
<div class="tile-container">
{% for i in posts %}
<div class="tile">
  <div style="font-size: small">
    {% if i.mail %}
    <a href="mailto:{{ i.mail }}">Anonymous</a>
    {% else %}
    Anonymous
    {% endif %} <br>
    Responses: {{ i.answ }}<br>
    {{ i.postDate }}<br>
  </div>
  {{ i.postContent | postprocess | safe }}
</div>
{% endfor %}
</div>
<center>snekboard</center>

templates/snekboard/form.html
<form action="{% url 'snekboard:postapi' b.boardUrl %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="parent" value="{{ parent }}">
  <table><tbody>
    <tr>
      <td>Email</td>
      <td><input type="text" name="mail"> {# not email because there's no @ in sage #}
          <input type="submit" value="Submit"></td>
    </tr>
    <tr>
      <td>Message</td>
      <td><textarea name="msg"></textarea></td>
    </tr>
    <tr>
      <td>Password</td>
      <td><input type="password" name="pass"></td>
    </tr>
  </tbody></table>
</form>

templates/snekboard/index.html
<h1>!</h1>
police is coming lmao

templates/snekboard/post.html
<center>
  <h1>/{{ b.boardUrl }}/</h1>
  <h2>{{ b.boardTitle }}</h2>
</center>
<hr>
<center>
  <h3>Reply</h3>
  {% include 'snekboard/form.html' with b=b parent=post.postId %}
</center>
<hr><hr>
<form action="{% url 'snekboard:postdelete' b %}" method="post">
  {% csrf_token %}
{% include 'snekboard/postsnippet.html' with b=b post=post deletable=True%}
<hr>
{% for i in ans %}
{% include 'snekboard/postsnippet.html' with b=b post=i deletable=True%}
{% endfor %}
  <input type="password" name="pass">
  <input type="Submit" value="Delete">
</form>
<center>snekboard</center>

templates/snekboard/postsPage.html
<center>
  <h1>/{{ b.boardUrl }}/</h1>
  <h2>{{ b.boardTitle }}</h2>
</center>
<hr>
<hr>
<center>
  {% include 'snekboard/form.html' with b=b parent=0 %}
</center>
<hr><hr>
{% for i in t %}
{% include 'snekboard/postsnippet.html' with b=b post=i.0 deletable=False %}
<blockquote>
{% if i.1 %} Skipped {{ i.1 }} posts.
<a href="{%url 'snekboard:post' b.boardUrl i.0.postId %}">Click here to view.</a>
<hr>
{% endif %}
{% for j in i.2 %}
{% include 'snekboard/postsnippet.html' with b=b post=j deletable=False%}
{% endfor %}
</blockquote>
{% endfor %}
<hr>
|
{% for i in p %}
<a href="{% url 'snekboard:postsPage' b.boardUrl i %}">{{ i }}</a> |
{% endfor %}
<hr>
<center>snekboard</center>

templates/snekboard/postsnippet.html
{% load snekboard_postprocess %}
<div style="font-size: small">
{% if deletable %}
<input type="radio" name="post" value="{{ post.postId }}">
{% endif %}
{% if post.mail %}<a href="mailto:{{ post.mail }}">Anonymous</a>{% else %}Anonymous{% endif %}
{{ post.postDate }}
<a href="{% url 'snekboard:post' b.boardUrl post.postId %}">{{post.postId}}</a></div>
{{ post.postContent | postprocess | safe }}
<hr>